AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template launches an EC2 instance to deploy web app by using CFN.

Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: ssh-key 
      SecurityGroups: 
        - ssh-key
      Tags:
        - 
          Key: Name
          Value: Cfn-Instance
      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          yum update -y
          yum install -y httpd 
          cd /var/www/html
          wget https://raw.githubusercontent.com/jb0071075/Kitten-Carousel/main/AWS-Project%20Folder/Kittens-Carousel-Static/static-web/index.html
          wget https://raw.githubusercontent.com/jb0071075/Kitten-Carousel/main/AWS-Project%20Folder/Kittens-Carousel-Static/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/jb0071075/Kitten-Carousel/main/AWS-Project%20Folder/Kittens-Carousel-Static/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/jb0071075/Kitten-Carousel/main/AWS-Project%20Folder/Kittens-Carousel-Static/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/jb0071075/Kitten-Carousel/main/AWS-Project%20Folder/Kittens-Carousel-Static/static-web/cat3.png
          systemctl start httpd
          systemctl enable httpd     
Outputs:
  WebisteUrl: 
    Description: Kittenn Carousel's URL address
    Value: !GetAtt CFNInstance.PublicDnsName

  